### ISSUE TITLE
Editor auto go back to the top

### ISSUE THREAD

**Issue by yzy1996** [Mathpix/vscode-mathpix-markdown#9]
When I type in the bottom of `.mmd` file, it will auto go back to the top of the interface.

I wonder it's a bug or the own problem of mine.

**Comment by montanaflynn** [comment]
Hi @yzy1996, I couldn't reproduce this exactly although I did find a similar problem where the editing side of the preview scrolled up partially when editing the bottom. This is happening because the preview is shorter than the content and it tries to keep the side by side. Thanks for reporting this, we'll look into possible solutions.

When you were editing the bottom of the file would the editor or preview side go back to to the very top?

**Comment by OlgaRedozubova** [comment]
@yzy1996 Do you have long lines in your `.mmd` file?

When using very long strings `vscode` does not sync edit and preview scrolling.
The issue in `vscode`
https://github.com/microsoft/vscode/issues/119578


![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/32493105/112975456-58564680-915c-11eb-9f49-df61c64bc06c.gif)

**Comment by montanaflynn** [comment]
@yzy1996 as a temporary fix I found turning off the following VS code setting fixes the problem while still keeping the preview scrolled to the editor:

<img width="633" alt="Screen Shot 2021-03-30 at 17 56 33" src="https://user-images.githubusercontent.com/24260/112978229-48049280-9181-11eb-8334-39b5a2e0f2ba.png">

You can disable it from the vscode settings page: https://code.visualstudio.com/docs/getstarted/settings

**Comment by yzy1996** [comment]
Thanks for the quick response! I really love this project. Thank you guys again!

@montanaflynn This scroll setting does fix my problem.  This exactly happens when I type many multi-line block mode mathematics, so it wants to sync the editor scrolled to the preview.

That's a couple of settings, you can also turn off 'Scroll Preview With Editor'.

@OlgaRedozubova Thanks but I did not have long lines.
